Gemfile.lock
README.md
app/controllers/qa_server/authority_validation_controller.rb
app/controllers/qa_server/monitor_status_controller.rb
app/loggers/qa_server/scenario_logger.rb
app/models/qa_server/scenario_run_history.rb
app/models/qa_server/scenario_run_registry.rb
app/models/qa_server/scenario_run_summary.rb
app/presenters/qa_server/check_status_presenter.rb
app/presenters/qa_server/monitor_status_presenter.rb
app/validators/qa_server/scenario_validator.rb
app/validators/qa_server/search_scenario_validator.rb
app/views/qa_server/check_status/index.html.erb
app/views/qa_server/monitor_status/index.html.erb
lib/generators/qa_server/templates/db/migrate/20180807045549_create_scenario_run_registry.rb.erb
lib/generators/qa_server/templates/db/migrate/20180807045552_create_scenario_run_history.rb.erb
lib/generators/qa_server/templates/db/migrate/20180807045554_drop_unused_tables.rb.erb
lib/generators/qa_server/templates/db/migrate/20180809045552_add_indices_to_scenario_run_history.rb.erb
lib/qa_server/version.rb
qa_server.gemspec
spec/test_app_templates/Gemfile.extra

* was saving just failures, but decided it was meaningful to know how long an authority had been up and running by including passing run data as well
* updates monitor status page to include a graph showing failing:passing test ratio
* updated to follow bixby rules in the new history code
Filter historical data to include only one run per day to avoid giving a false impression on the length of time an authority has been installed.  Multiple runs can occur on a day when `refresh` parameter is passed to the monitor status page during app interactive testing.

refactor history data to include passing test data

---

app/presenters/qa_server/navmenu_presenter.rb
app/views/layouts/qa_server.html.erb
config/locales/qa_server.en.yml
lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/qa_server/configuration.rb
qa_server.gemspec

Allows apps to extend the main nav menu.  This allows apps to install API docs and have a menu item that goes to the docs.

drive main nav menu from presenter

---

CHANGELOG.md
lib/qa_server/version.rb

* change css class for failing tests to allow pingdom to check for the css class and notify sysop
* temporarily disable direct access to AGROVOC
* add vocabs: locperformance_ld4l_cache and locdemographics_ld4l_cache

prep for 1.2.3 release

---

.github/ISSUE_TEMPLATE/new_dataset_request.md

Moved guiding instructions from https://wiki.duraspace.org/display/LD4P2/Request+a+New+Dataset+For+QA directly into the issue template.

Updates to the request template, guiding info in one place

---

.gitignore
app/assets/stylesheets/qa_server/_monitor-status.scss
app/controllers/qa_server/monitor_status_controller.rb
app/models/qa_server/performance_history.rb
app/prepends/prepended_linked_data/find_term.rb
app/prepends/prepended_linked_data/search_query.rb
app/presenters/qa_server/monitor_status_presenter.rb
app/views/qa_server/monitor_status/index.html.erb
config/locales/qa_server.en.yml
lib/generators/qa_server/config_generator.rb
lib/generators/qa_server/templates/db/migrate/20190813045549_create_performance_history.rb.erb

Work in this PR...
* UI to display performance data as graphs on the monitor status page
* saves search query & term fetch performance data to database for every request
* calculates averages for load, normalization, and combined times
* calculates averages for last 24 hours, last 30 days, and last 12 months
Currently splits on time periods: day, month, year
Might also want to split on:
* action: fetch, search
* per authority

add performance data to monitor status page

---

app/models/qa_server/performance_history.rb
app/presenters/concerns/qa_server/monitor_status/performance_datatable_behavior.rb
app/presenters/concerns/qa_server/monitor_status/performance_graph_behavior.rb
app/services/qa_server/performance_calculator_service.rb
app/services/qa_server/performance_graph_data_service.rb
app/services/qa_server/performance_graphing_service.rb
lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/qa_server/configuration.rb

* switch performance graph to stacked_bar
* don’t calculate low and high for graphs since they aren’t used
* don’t calcualte full request data for graphs since it isn’t used
* fix a few rubocop errors

switch performance graph to stacked_bar

---

CHANGELOG.md
app/prepends/prepended_linked_data/find_term.rb
app/prepends/prepended_linked_data/search_query.rb

If QA doesn’t return performance data, then just return the results without trying to process the non-existent performance data.  This fixes an exception that was thrown when fetching with format=jsonld.

do not extract and attempt to save non-existent performance data

---

app/assets/stylesheets/qa_server/_authorities.scss
app/assets/stylesheets/qa_server/_check-status.scss
app/assets/stylesheets/qa_server/_monitor-status.scss
app/models/concerns/qa_server/performance_history_data_keys.rb
app/models/qa_server/performance_history.rb
app/prepends/prepended_linked_data/find_term.rb
app/prepends/prepended_linked_data/search_query.rb
app/prepends/prepended_rdf/rdf_graph.rb
app/presenters/concerns/qa_server/monitor_status/performance_datatable_behavior.rb
app/presenters/concerns/qa_server/monitor_status/performance_graph_behavior.rb
app/presenters/qa_server/monitor_status_presenter.rb
app/services/qa_server/performance_calculator_service.rb
app/services/qa_server/performance_graph_data_service.rb
app/services/qa_server/performance_graphing_service.rb
app/views/qa_server/monitor_status/_performance.html.erb
config/locales/qa_server.en.yml
lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/generators/qa_server/templates/db/migrate/20191007134527_update_performance_history_table.rb.erb
lib/qa_server/configuration.rb

Performance graphs are created for all combinations of...
* authority:  each authority + all authorities
* time period: :day, :month, :year
* action: :all_actions, :search, :fetch
This produces 9 graphs per authority plus 9 more that include data from all authorities.
The performance data table splits details into combinations for...
* authority:  each authority + all authorities
* 10th percentile (fastest), average, 90th percentile (slowest)
* action: :all_actions, :search, :fetch
* task: :retrieve, :graph_load, :normalization, :full_action (labeled TOTAL)
where...
* :retrieve includes network costs + cache/authority processing for retrieving data from the cache or directly from an authority
* :graph_load includes the time to load the retrieved data into an RDF::Graph
* :normalization …

Rework performance data to add calculations/UI display per action

---

lib/generators/qa_server/templates/config/authorities/linked_data/agrovoc_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/dbpedia_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/geonames_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/getty_aat_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/getty_tgn_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/getty_ulan_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/locdemographics_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/locnames_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/locnames_rwo_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/locperformance_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/mesh_nlm_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/nalt_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/oclcfast_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/rda_registry_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locperformance_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/rda_registry_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/wikidata_direct_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/wikidata_direct.json

* adds pagination start_record parameter for LD4P cached data
* adds RDA Registry authority
* splits LCNAF into 2 authorities for LD4P cached data focused locnames and real world object focused locnames_rwo
* adds wikidata authority - NOTE: The first pass on fetching through this authority is non-performant.

update authorities with pagination; add RDA Registry and wikidata; split LCNAF

---

CHANGELOG.md
lib/qa_server/version.rb

NOTE: Was going to release as 3.0.4, but the change to add request_header forced a parameter change in the prepends for find and query.  This seemed to warrant a major release as the public signature has changed.

prep for release 4.0.0

---

CHANGELOG.md
lib/qa_server/version.rb

* bug fix - move individual params into request header to avoid lost subauths during testing

prep release of 5.0.2

---

app/prepends/prepended_linked_data/find_term.rb
app/prepends/prepended_linked_data/search_query.rb
lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/qa_server/configuration.rb

Performance data is gathered on every request.  During peak access times, this can become a performance drain itself.  This allows performance data gathering to be stopped when needed.

allow suppression of performance data gathering

---

CHANGELOG.md
lib/qa_server/version.rb

NOTE: Two commits were made without a PR.  They comprise the 5.2.0 release.
Look for commits with title…
* set monitoring to expire nightly at 3am ET by default
* save performance data once a day when running monitoring tests
Also includes changes from PRs...
* setup travis-ci to run

prep for release 5.2.0

---

lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/qa_server/configuration.rb

Missed adding defaults to qa_server.rb initializer in generator templates.  Added defaults for preferred_time_zone_name and hour_offset_to_run_monitoring_tests configs.

add defaults to configuration initializer

---

app/prepends/prepended_services/graph_service.rb
lib/generators/qa_server/config_generator.rb

This prepend is no longer needed.  The logging happening in the original commit has been moved to QA release 5.3.0.

Revert logging of graph load failures - Moved logging to QA

---

.travis.yml
CHANGELOG.md
lib/qa_server/version.rb

* optionally log browser and platform user agent info
* update to qa 5.3
* add a request id to the search and find request headers
* log exception for graph load failures
* optionally include IP info at start of search/find linked data requests

prep release 5.3.0

---

lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/qa_server.rb
lib/qa_server/configuration.rb
qa_server.gemspec
spec/lib/qa_server_spec.rb

* adds config hour_offset_to_expire_cache
* deprecates config hour_offset_to_run_monitoring_tests (replaced by hour_offset_to_expire_cache)
* updates QaServer.monitoring_expires_at to use the new hour_offset_to_expire_cache config
* adds QaServer.cache_expiry that can be used for expiring all cached data

add cache_expiry returning seconds until cache should expire

---

CHANGELOG.md
lib/qa_server/version.rb

* adds config hour_offset_to_expire_cache
* deprecates config hour_offset_to_run_monitoring_tests (replaced by hour_offset_to_expire_cache)
* updates QaServer.monitoring_expires_at to use the new hour_offset_to_expire_cache config
* adds QaServer.cache_expiry that can be used for expiring all cached data
* add tests and exceptions for configs

prep for release 5.4.0

---

.rubocop.yml
app/controllers/qa_server/monitor_status_controller.rb
app/models/qa_server/performance_cache.rb
app/models/qa_server/performance_history.rb
app/models/qa_server/scenario_run_history.rb
app/models/qa_server/scenario_run_registry.rb
app/models/qa_server/scenario_run_summary.rb
app/prepends/prepended_rdf/rdf_graph.rb
app/presenters/qa_server/monitor_status/current_status_presenter.rb
app/services/qa_server/performance_graph_data_service.rb
lib/generators/qa_server/templates/config/initializers/qa_server.rb
lib/qa_server/configuration.rb

Cached…
* summary table data for latest run
* failures for latest run, if any
* authority connection history
* performance graph data
* performance data table data
Allows forced refresh in the same way as done previously.

use caching with expiry for monitor status page

---

CHANGELOG.md
lib/qa_server/version.rb

Use caching with expiry for monitor status page.
Cached…
* summary table data for latest run
* failures for latest run, if any
* authority connection history
* performance graph data
* performance data table data
Allows forced refresh in the same way as done previously.

prep for release 5.5.0

---

README.md
app/controllers/qa_server/monitor_status_controller.rb
app/jobs/qa_server/monitor_tests_job.rb
lib/qa_server/configuration.rb

Process prior to this PR ran monitoring tests inline.  They take > 30m to complete.  This caused Pingdom to timeout and report an error.  With this PR, the 3am Pingdom check will use the current data and kick off the background process to run the tests.  The 4am Pingdom check will report the actual up/down status.

run monitoring tests in background

---

app/controllers/qa_server/monitor_status_controller.rb
app/jobs/qa_server/monitor_tests_job.rb
app/models/qa_server/performance_history.rb
app/models/qa_server/scenario_run_history.rb
app/presenters/concerns/qa_server/monitor_status/performance_datatable_behavior.rb
app/presenters/qa_server/monitor_status_presenter.rb
app/services/qa_server/performance_calculator_service.rb
app/services/qa_server/performance_datatable_service.rb
app/services/qa_server/performance_graph_data_service.rb
app/services/qa_server/performance_graphing_service.rb

Refactor includes…
* commit performance data before calculating
* cache performance graph data expiring once per day for month and year data
* cache performance graph data expiring on the hour
* calculate last hour of performance data for Day graphs (This is the only calculation that happens everytime the monitor status page loads.)

refactor generation of performance graphs

---

CHANGELOG.md
lib/qa_server/version.rb

* refactor generation of performance graphs to minimize db access and calculations
* shorten race_condition times for caching
* rename jobs_logger to be monitor_logger
* run monitoring tests in background
* move methods from QaServer to services
* use presenter to get failure data
* move controller validation code to module include
* limit historical data to configurable time period
* move time_period where clause construction to service

prep for release 6.0.0

---

CHANGELOG.md
lib/qa_server/version.rb

* change historical summary to show number of days instead of number of tests (original intent)
* default tests to connection tests
* update authorities to v2.2 configs
* add authority cerl_ld4l_cache

prep for release 6.1.0

---

app/controllers/qa_server/check_status_controller.rb
app/controllers/qa_server/monitor_status_controller.rb
app/jobs/qa_server/monitor_tests_job.rb
app/models/qa_server/performance_cache.rb
app/models/qa_server/scenario_run_history.rb
app/services/qa_server/performance_datatable_service.rb
app/services/qa_server/performance_graph_data_service.rb
app/services/qa_server/performance_graphing_service.rb
lib/qa_server/configuration.rb

Also…
* set all monitor_logger messages to debug
* set all performance_cache_logger messages to debug
* add enable/disable_monitor_status_logging config
* add enable/disable_performance_cache_logging config
By default (according to Rails logger default behaviors), logging in development environment is enabled and logging in production environment is disabled.

add performance cache logger

---

app/cache_processors/concerns/qa_server/cache_keys.rb
app/cache_processors/qa_server/cache_expiry_service.rb
app/cache_processors/qa_server/performance_daily_graph_cache.rb
app/cache_processors/qa_server/performance_datatable_cache.rb
app/cache_processors/qa_server/performance_hourly_graph_cache.rb
app/cache_processors/qa_server/performance_monthly_graph_cache.rb
app/controllers/qa_server/monitor_status_controller.rb
app/services/qa_server/performance_datatable_service.rb

also cleans up…
* include _CACHE_KEY in the name of cache key constants
* log generation of performance graphs once per time period

move performance datatable cache control to cache_processors

---

app/cache_processors/concerns/qa_server/cache_keys.rb
app/cache_processors/qa_server/performance_daily_graph_cache.rb
app/cache_processors/qa_server/performance_hourly_graph_cache.rb
app/cache_processors/qa_server/performance_monthly_graph_cache.rb
app/cache_processors/qa_server/scenario_history_cache.rb
app/cache_processors/qa_server/scenario_run_cache.rb
app/cache_processors/qa_server/scenario_run_failures_cache.rb
app/cache_processors/qa_server/scenario_run_summary_cache.rb
app/controllers/qa_server/monitor_status_controller.rb
app/models/qa_server/scenario_run_history.rb

includes caching for...
* scenario run summary
* scenario run failures
* scenario history
* running of connection tests controlled by cache time marker
also cleans up…
* yardoc missing for force parameter
* removed deprecated #run_results

move caching of summary and historical data to cache_processors

---

CHANGELOG.md
lib/qa_server/version.rb

* refactor of caching system to simplify the process
* rename monitor_cache_service to cache_expiry_service
* move generation of hourly graph to cache_processors
* move generation of daily and monthly graphs to cache_processors
* move performance datatable cache control to cache_processors
* move caching of summary and historical data to cache_processors
* move caching of test execution marker to cache_processors
* move performance cache of performance data to cache_processors

release 7.0.0

---

app/cache_processors/concerns/qa_server/cache_keys.rb
app/cache_processors/qa_server/scenario_history_cache.rb
app/cache_processors/qa_server/scenario_history_graph_cache.rb
app/controllers/qa_server/monitor_status_controller.rb
app/presenters/concerns/qa_server/monitor_status/performance_graph_behavior.rb
app/presenters/qa_server/monitor_status/current_status_presenter.rb
app/presenters/qa_server/monitor_status/history_presenter.rb
app/presenters/qa_server/monitor_status/performance_presenter.rb
app/services/qa_server/history_graphing_service.rb
app/services/qa_server/performance_graphing_service.rb
app/views/qa_server/monitor_status/_performance.html.erb
app/views/qa_server/monitor_status/_test_history.html.erb
app/views/qa_server/monitor_status/_test_summary.html.erb

* created history_graph_service to generate the graph
* created scenario_history_cache to cache the generation of the graph
Also cleanup…
* performance_grarphing_service uses same method names as history_graphing_service
* log warning in monitor logger if graph failed to create
* monitor_status page won’t try to display graphs if the graph files do not exist
* move checks for missing data from views to presenters

move generation of history graph

---

app/cache_processors/qa_server/performance_cache.rb
app/jobs/qa_server/monitor_tests_job.rb

The normal processing is for the monitoring tests to run once per day.  The rest of the time cached data is used to display the monitor status page.
A side effect of running the tests is that a large amount of performance data is saved in the performance cache.  This PR writes out the performance cache and starts fresh with an empty cache.

write out cache after completing monitor tests run

---

CHANGELOG.md
app/services/qa_server/performance_graph_data_service.rb
lib/qa_server/version.rb

Making text 1 blank character fixes the problem.

release 7.2.1 - fix graph fails to display when text is empty string

---

app/cache_processors/qa_server/job_id_cache.rb
app/jobs/qa_server/monitor_tests_job.rb

Justification: follow single responsibility principle
Prepare for reuse in graph jobs.

move job id cache to sepearate cache class

---

app/cache_processors/concerns/qa_server/cache_keys.rb
app/cache_processors/qa_server/performance_monthly_graph_cache.rb
app/cache_processors/qa_server/performance_year_graph_cache.rb
app/controllers/qa_server/monitor_status_controller.rb
app/jobs/qa_server/performance_monthly_graph_job.rb
app/jobs/qa_server/performance_year_graph_job.rb
app/services/qa_server/performance_graphing_service.rb

* moves graph generation to background job
* renames monthly to year to avoid confusion with month graph
* remove cache of performance year graph data
RE: cache removal - Now that the kickoff of the graph generation process is cached and calls the performance year graph job when expired, the cache of the data is no longer needed.  Everytime the job is executed, the data will need to be generated.  There is a cache of the job_id to prevent race conditions.

move performance year graph generation to background job

---

app/cache_processors/concerns/qa_server/cache_keys.rb
app/cache_processors/qa_server/performance_month_graph_cache.rb
app/cache_processors/qa_server/performance_year_graph_cache.rb
app/controllers/qa_server/monitor_status_controller.rb
app/jobs/qa_server/history_graph_job.rb
app/jobs/qa_server/performance_month_graph_job.rb
app/jobs/qa_server/performance_year_graph_job.rb
app/services/qa_server/performance_graphing_service.rb

Also, rename daily to month to avoid confusion with day graph.
These are the same changes that were made for the year graph.  See PR #330.

move performance month graph generation to background job

---

app/cache_processors/concerns/qa_server/cache_keys.rb
app/cache_processors/qa_server/cache_expiry_service.rb
app/cache_processors/qa_server/performance_day_graph_cache.rb
app/controllers/qa_server/monitor_status_controller.rb
app/jobs/qa_server/performance_day_graph_job.rb
app/jobs/qa_server/performance_month_graph_job.rb
app/services/qa_server/performance_graph_data_service.rb
app/services/qa_server/performance_graphing_service.rb

* rename hourly to day to be consistent with processing of other performance graphs
* removes data cache for day and month graph.  
RE: cache removal - See note about data caching for performance graphs in PR #330 which moved year graph to background job.
Related Work:
* #330 move performance year graph generation to background job
* #331 move performance month graph generation to background job

move performance day graph generation to background job

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/getty_aat_ld4l_cache_validation.yml

Currently one has to add a space after a search term for many searches before results that make sense will come up.

precious (without a space) test

---

app/loggers/qa_server/scenario_logger.rb
app/models/qa_server/authority_scenario.rb
app/models/qa_server/search_scenario.rb
app/validators/qa_server/scenario_validator.rb
app/validators/qa_server/search_scenario_validator.rb
app/validators/qa_server/term_scenario_validator.rb
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/dbpedia_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml
lib/qa_server/configuration.rb
spec/feature/accuracy_spec.rb
spec/spec_helper.rb

Prevents accuracy tests from running in Travis as it is not uncommon for some tests to fail.  This is not a reflection on the functioning of the qa_server code.  It is an analysis of the ability of authority providers to accurately find resources.
This PR also includes...
* add request_data to status_logger (e.g. query for search , identifier for term)
* fix/add yardoc for data being passed in/returned
* deprecate mispelled methods (i.e. datails become details)
* set defaults for QaServer configs to not write out performance data and to set the time zone

Run accuracy tests with rspec for regression testing

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/nalt_ld4l_cache_validation.yml

I agree that this vocab doesn't have a demonstrated need for subauths and the list is probably a copy and paste error.

Accuracy tests for NALT

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/nalt_ld4l_cache_validation.yml

I'm not sure if identifier should have single or double quotes when the value is a URI. I've seen it both ways.

Normalizing syntax to be more consistent

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml

I'm not sure if single or double quotes should be used when there's a URI for the identifier value. I've seen it both ways.

Normalized syntax to be consistent

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/geonames_ld4l_cache_validation.yml

Not adding  a lot of subauth test right now. No profiles seem to be using this looking up and the geonames ontology isn't particularly easy to interpret with respect to Feature subclasses. Normalized syntax too.

Fixed URI and added one subauth test

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml

Adding tests for Issue #201
* adds with diacritics
* adds without diacritics
* adds with name in Japanese
not found     LOCNAMES_RWO_LD4L_CACHE:person:Tanaka, Shozo
not found     LOCNAMES_RWO_LD4L_CACHE:person:Tanaka, Shōzō
not found     LOCNAMES_RWO_LD4L_CACHE:person:田中正造
found at 12; expected by 5   LOCNAMES_RWO_W_LD4L_CACHE:person:Tanaka, Shōzō

add accuracy test for Tanaka, Shōzō

---

spec/feature/accuracy_spec.rb

performs the following checks in order for each accuracy validation scenarios:
* was there an error?
* is there any data?
* is the expected URI somewhere in the data?
* is the expected URI at the desired position or better?

make each accuracy test have a single outcome

---

lib/generators/qa_server/templates/config/authorities/linked_data/getty_aat_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/getty_tgn_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/locvocabs_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/getty_ulan_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locvocabs_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/rda_registry_ld4l_cache_validation.yml

* add extended context for
* getty_aat_ld4l_cache
* getty_tgn_ld4l_cache
* add authorities
* locvocabs_ld4l_cache
* adjust validations
* fix a few syntax errors
* adjust result_size for validations that return less than 200 chars when passing
* remove term connection tests when fetch term is not supported

sync authorities configs and validations with production lookup

---

lib/generators/qa_server/templates/config/authorities/linked_data/locnames_rwo2_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/locnames_rwo3_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/agrovoc_direct_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/cerl_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/dbpedia_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/geonames_direct_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/geonames_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/getty_aat_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/getty_tgn_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/getty_ulan_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locsubjects_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/nalt_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclc_fast_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_direct_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/rda_registry_ld4l_cache_validation.yml

Also...
* fixes typo in `position` and removes duplicate test
* splits LOC_RWO into 3 sets of tests of about 9 tests each
* changes subject_uri of RDA_REGISTRY/colour_content q=polychrome, but may be an incorrect change.  See notes below...
Not sure of the subject URI for RDA_REGISTRY polychrome search in subauth colour_content.  I'm seeing different URIs in LD4P/qa_server and cult-it/qa_server.  Both versions fail.
```
subject_uri: "http://rdaregistry.info/termList/RDAColourContent/1003"	
subject_uri: "http://rdaregistry.info/termList/RDACartoDT/1003"
```

add pending to failing validation tests

---

CHANGELOG.md
lib/qa_server/version.rb

* UI improvements of check_status page
* pre-populate selection fields with most recently submitted authorities
* add ability to compare two authorities' accuracy tests in UI
* update check_status UI to require GO button click to start processing
* fix javascript to avoid referencing missing elements
* accuracy test updates
* accuracy tests default to `context=false` since it is not required for testing
* allow accuracy tests through rspec to be marked pending (allows for better regression testing)
* add pending to failing validation tests such that accuracy_spec passes
* sync tests with production accuracy tests
* fix typo in `position` and a few syntax errors
* adjust result_size for validations where passing tests return less than 200 chars
* split locnames_rwo_ld4l_cache into 3 sets …

prep release v7.5.0

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_ld4l_cache_validation.yml

http://id.loc.gov/authorities/names/n80010449.

Fixed URI Camden, N.J.

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/geonames_ld4l_cache_validation.yml
lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/getty_ulan_ld4l_cache_validation.yml

Remove pending from all geonames validations.
Add pending to all getty_ulan validations.

sync authority configs and validations

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml

The test doesn't pass because the deprecated entity is in a different data set.

Deleting Cookery Test

---

qa_server.gemspec

If these gems are dependencies instead of development_dependencies, OCLCFAST_DIRECT fails to get any data back as RDF.  Instead, it comes back as XML.  It is not clear why this happens and may not have happened outside of the .internal_test app.  But since it is not required for these to be direct dependencies, they were switched back to development_dependencies.

do not directly include linkeddata and qa gems

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_direct_validation.yml

OCLC is in the process of splitting events and meetings.  During the transition, the resutls of queries to both these subauths can be unpredictable.  Especially for events, so the event connection test is temporarily turned off.
See Issue #327

do not run OCLCFAST_DIRECT event connection test

---

lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/mesh_nlm_ld4l_cache_validation.yml

Connection tests are meant to verify that the authority is up and accessible.  They do not have to fully test all aspects of the authority.  There is already a connection test for the subject subauth.  So the failure of Spain was moved to the accuracy tests.

move Spain subject to accuracy tests

---

lib/generators/qa_server/templates/config/authorities/linked_data/getty_tgn_ld4l_cache.json
lib/generators/qa_server/templates/config/authorities/linked_data/getty_ulan_ld4l_cache.json

* fixes the ldpath for label in both TGN and ULAN
* fixes getty and skosxl prefixes in both
* adds context for ULAN
* expands context for TGN
* sets id to the subjectURI in the results
NOTE: id should be `dc:identifier`, but that predicate is not in the search results.
See issues:
* [#419](https://github.com/LD4P/qa_server/issues/419) - Getty TGN blank id and label in primary result data (new indexing)
* [#420](https://github.com/LD4P/qa_server/issues/420) - Getty ULAN blank id and label in primary result data (new indexing)

fix id and label for Getty TGN and ULAN

---

CHANGELOG.md
lib/qa_server/version.rb

* update authority configs and test scenarios to use the new cache indexing with results stored as blobs in the index
* update to Rails 5.2.5
* update dependencies
* fix exception when first time running monitor status

release v7.6.0

---

CHANGELOG.md
app/assets/stylesheets/qa_server/_check-status.scss
app/presenters/qa_server/check_status_presenter.rb
app/views/qa_server/check_status/index.html.erb
config/locales/qa_server.en.yml

Fixes #445
Changes:
* add css to dogear pending accuracy tests
* remove option to run all tests on check status page
This allows for quick identification through the UI whether a test is expected to fail.  It also allows for quick identification of a test that used to fail and now passes indicating the pending tag should be removed from the test.

dogear pending accuracy tests

---

CHANGELOG.md
app/presenters/qa_server/check_status_presenter.rb
app/views/qa_server/check_status/index.html.erb
lib/qa_server/version.rb

Checking status when doing a comparison of two authorities receives a Symbol instead of the status hash.  The simple fix is to use use the passed in status Symbol and not worry about marking tests pending when doing a comparison.

fix compare accuracy and release 7.9.1

---

CHANGELOG.md
app/presenters/qa_server/check_status_presenter.rb
lib/qa_server/version.rb

To avoid an exception, only check for pending tests and set the dogear style if status is a Hash.

Release 7.9.2 with FIX: only check for dogear if status is a Hash

---

CHANGELOG.md
README.md
lib/qa_server/version.rb
qa_server.gemspec

See https://github.com/cul-it/qa_server/issues/386
In order to update Ruby and Rails in [qa_server_container](https://github.com/LD4P/qa_server_container), Rails must be updated to 7.0 here.

Update Rails dependency; bump to v8.0.0

---

app/prepends/prepended_rdf/rdf_graph.rb
lib/qa_server/version.rb

- Fixes rdf reader ArgumentError due to ruby 3 changes in handling positional and keyword arguments: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

Release 8.0.1
