- app/models/qa_server/term_scenario.rb
- lib/generators/qa_server/templates/config/authorities/linked_data/mesh_ld4l_cache.json
> use fetch when possible to avoid browser decoding of %2E

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml
https://github.com/LD4P/qa_server/commit/4eac037157854026345b6afcd74e8ddce106d74d
> Adding accuracy tests locdemographics_ld4l_cache_validation.yml

- lib/generators/qa_server/templates/config/authorities/linked_data/DISABLED/agrovoc_direct.json
- lib/generators/qa_server/templates/config/authorities/linked_data/agrovoc_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/dbpedia_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/geonames_direct.json
- lib/generators/qa_server/templates/config/authorities/linked_data/geonames_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/getty_aat_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/getty_tgn_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/getty_ulan_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/locdemographics_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/locgenres_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/locnames_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/locperformance_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/locsubjects_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/mesh_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/nalt_ld4l_cache.json
- lib/generators/qa_server/templates/config/authorities/linked_data/oclcfast_direct.json
- lib/generators/qa_server/templates/config/authorities/linked_data/oclcfast_ld4l_cache.json
> add `encode: true` to search query param for all 2.0 configs

- app/presenters/concerns/qa_server/monitor_status/performance_datatable_behavior.rb
- app/services/qa_server/performance_calculator_service.rb
- app/services/qa_server/performance_graphing_service.rb
- app/views/qa_server/monitor_status/_performance.html.erb
- config/locales/qa_server.en.yml
Fixes...
* make sure count is counting based on the current set of times
* add in missing translations
* fix performance data table data style for retrieve
* unsupported_action? for performance datatable handles all 0 stats
* use old :load data when split :retrieve and :graph_load are not available
> Fix bugs for v3.0.0

- CHANGELOG.md
- lib/qa_server/version.rb
* remove titles from graphs (previously set to '' which caused problems when deployed)
> update to release 3.0.3

- app/prepends/prepended_linked_data/find_term.rb
- app/prepends/prepended_linked_data/search_query.rb
* add request_header
* get performance_data setting from request_header or parameter
> updates for qa 4.2.5 changes to search and find methods

- CHANGELOG.md
- lib/qa_server/version.rb
* bug fix - use correct parameters for search query
> prep for release 5.0.3

- CHANGELOG.md
- lib/qa_server/version.rb
* fix - add defaults to the initializer generator template for new configs
> prep release 5.2.1

- app/views/qa_server/monitor_status/_performance.html.erb
- app/views/qa_server/monitor_status/_test_history.html.erb
- app/views/qa_server/monitor_status/_test_summary.html.erb
Not sure what is causing the nils, but the page shouldn't fail when this happens.
> check for nil before calling .each

- app/controllers/qa_server/monitor_status_controller.rb
- app/models/qa_server/performance_cache.rb
- app/models/qa_server/performance_history.rb
- app/models/qa_server/scenario_run_history.rb
- app/models/qa_server/scenario_run_registry.rb
- app/prepends/prepended_linked_data/find_term.rb
- app/prepends/prepended_linked_data/search_query.rb
- app/prepends/prepended_rdf/rdf_graph.rb
- app/presenters/concerns/qa_server/monitor_status/performance_datatable_behavior.rb
- app/presenters/qa_server/monitor_status/current_status_presenter.rb
- app/presenters/qa_server/monitor_status/history_presenter.rb
- app/services/qa_server/monitor_cache_service.rb
- app/services/qa_server/performance_graph_data_service.rb
- app/services/qa_server/time_period_service.rb
- app/services/qa_server/time_service.rb
- app/validators/qa_server/scenario_validator.rb
- app/validators/qa_server/search_scenario_validator.rb
- lib/qa_server.rb
- spec/lib/qa_server_spec.rb
- spec/services/qa_server/monitor_cache_service_spec.rb
- spec/services/qa_server/time_period_service_spec.rb
- spec/services/qa_server/time_service_spec.rb
Moves methods related to time to TimeService and methods related to caching to MonitorCacheService.
> move methods from QaServer to services

- app/controllers/qa_server/monitor_status_controller.rb
- app/jobs/qa_server/monitor_tests_job.rb
- app/models/qa_server/performance_cache.rb
- app/services/qa_server/performance_graphing_service.rb
- lib/qa_server/configuration.rb
* set path in ENV[‘MONITOR_LOG_PATH’]
* default path `log/monitor_log`
> rename jobs_logger to be monitor_logger

- CHANGELOG.md
- lib/qa_server/version.rb
* empty performance cache after running monitor status tests
> release v7.1.1

- app/cache_processors/qa_server/performance_cache.rb
- app/prepends/prepended_linked_data/find_term.rb
- app/prepends/prepended_linked_data/search_query.rb
- app/prepends/prepended_rdf/rdf_graph.rb
- lib/qa_server/configuration.rb
- spec/lib/configuration_spec.rb
* make configs that return true/false end with ?
* add tests for configs that weren’t tested
* fix bugs in config#convert_size_to_bytes in response to testing
> add tests for recently added configs

- CHANGELOG.md
- lib/qa_server/version.rb
* make configs that return true/false end with ?
* add tests for configs that weren’t tested
* fix bugs in config#convert_size_to_bytes in response to testing
> release 7.1.2

- CHANGELOG.md
- lib/qa_server/version.rb
* move graphs from assets to public directory
> release 7.2.0

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml
> Increase precision

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/geonames_ld4l_cache_validation.yml
Added subauth: populated place and improved relevancy for Chicago
> subauth: populated place and improved relevancy

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/dbpedia_ld4l_cache_validation.yml
In Sinopia, "Volleyball" doesn't produce http://dbpedia.org/resource/Volleyball in the top 8 results. See the screenshot in https://docs.google.com/document/d/1UxSeZ9xWpIZ__UxzMAtJGlXUrRzY-yZ3OukZNw2FDrg/edit?usp=sharing.
> Relevancy test for volleyball

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/agrovoc_direct_validation.yml
Mix of preferred label, alt labels, language strings.
> Accuracy tests for Agrovoc

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml
Still need to square the subauths for topic and form based on intangibles. Currently we have them lumped in concepts. Eventually we'll need a meeting test.
> Some accuracy tests for FAST

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locnames_rwo_ld4l_cache_validation.yml
Adding tests for Issue #201
* with diacritics
* without diacritics
* with parenthetical
* without parenthetical
* translated languages including double byte languages
**Authority:** LOCNAMES_RWO_LD4L_CACHE:
**Subauthority:** person
TBD
> add more diacritic/special character accuracy tests

- app/loggers/qa_server/scenario_logger.rb
- app/models/qa_server/search_scenario.rb
- app/validators/qa_server/search_scenario_validator.rb
- spec/feature/accuracy_spec.rb
> allow accuracy tests to be marked as pending

- app/assets/stylesheets/qa_server/_check-status.scss
- app/controllers/qa_server/check_status_controller.rb
- app/presenters/qa_server/check_status_presenter.rb
- app/views/qa_server/check_status/index.html.erb
* improve CSS for comparison table
* only use comparison authority name if user requests comparison
* populate authority selection boxes with previous submitted values onLoad
* clean up javascript to avoid trying to set values on non-existent elements
>  Various form and data display improvements

- CHANGELOG.md
- config/i18n-tasks.yml
- config/locales/qa_server.en.yml
- lib/qa_server/version.rb
- qa_server.gemspec
- spec/i18n_spec.rb
Marked pending translations tests for unused translations and normalization of translations.
> release 7.5.1 - add missing translations

- lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/oclcfast_ld4l_cache_validation.yml
Given the number of works with Scream in the title, loosening this one.
> Loosening the Scream requirement

- app/presenters/qa_server/monitor_status/history_presenter.rb
> loosen threshold for caution in historical uptime table

- app/models/qa_server/scenario_run_history.rb
> hide data in Authority Connection History for non-active authorities

- app/controllers/qa_server/monitor_status_controller.rb
- config/locales/qa_server.en.yml
- spec/i18n_spec.rb
> show notification when refreshing starts on monitor status page

- CHANGELOG.md
- lib/qa_server/version.rb
* remove unused translations
* show notification when refreshing starts on monitor status page
* hide data in Authority Connection History for non-active authorities
* loosen threshold for caution in historical uptime table
* minor tweaks missed in original sync
> release v7.7.0 - UI improvements

- .rubocop_fixme.yml
- app/presenters/qa_server/monitor_status/history_presenter.rb
- spec/presenters/qa_server/monitor_status/history_presenter_spec.rb
adds documentation of data structures and for methods
> add tests for percent failure background css
